### ISSUE TITLE
removeAllChangeListeners vs removeChangeListener

### ISSUE THREAD

**Issue by rlatapy-luna** [michaelbukachi/realm-koroutines#6]
Is there any reason `removeAllChangeListeners()` is used instead of `removeChangeListener(listener)`?

https://github.com/michaelbukachi/realm-koroutines/blob/f1594ff9e0647b334c0b0d642b1b846bf7888e8f/realmkoroutines/src/main/java/com/michaelbukachi/realmkoroutines/realm.kt#L103

**Comment by michaelbukachi** [comment]
@rlatapy-luna Interesting observation. I really don't know why I went with `removeAllChangeListeners` :thinking:
